### ISSUE TITLE
Help Please?

### ISSUE THREAD

**Issue by AmpedgamR** [modeosr/source-engine-modea-bots#3]
привет, может кто-нибудь помочь мне с неизвестной командой "botrix"?

**Comment by defolity** [comment]
Это фейк, оно и не будет работать

**Comment by modeosr** [comment]
> Это фейк, оно и не будет работать

стульчик ты ахуел??? это не фейк на пк 100% будет работать а на телефон 60%

**Comment by modeosr** [comment]
> привет, может кто-нибудь помочь мне с неизвестной командой "botrix"?

botrix bot add добавить бота
botrix bot add добавить бота с ником
botrix bot kick кикнуть рандомного бота
botrix wp auto 1 бот само обучаеться защёд того как вы бегаете на карте

удачи!

**Comment by Sergii03** [comment]
> > Это фейк, оно и не будет работать
> 
> стульчик ты ахуел??? это не фейк на пк 100% будет работать а на телефон 60%

На телефоне 0% что оно будет работать.

**Comment by Sergii03** [comment]
1. Один мой друг проверял, и оно не работает.
2. Ты хочешь либы для Windows и Linux x86_64 запустить на Андроиде который под arm без эмуля?

**Comment by AmpedgamR** [comment]
хорошо, если он не работает на телефоне, тогда я закрываю проблему

**Comment by modeosr** [comment]
> > > Это фейк, оно и не будет работать
> > 
> > 
> > стульчик ты ахуел??? это не фейк на пк 100% будет работать а на телефон 60%
> 
> На телефоне 0% что оно будет работать.

в таком случае я сделаю make

**Comment by modeosr** [comment]
> 1. Один мой друг проверял, и оно не работает.
> 
>     2. Ты хочешь либы для Windows и Linux x86_64 запустить на Андроиде который под arm без эмуля?

я компилировал заранее для arm64 такчто у 60% должно работать... потом я сюда залью исходники и make и сделаю заранее скомпилированые файлы

**Comment by Sergii03** [comment]
> > 1. Один мой друг проверял, и оно не работает.
> >    
> >    2. Ты хочешь либы для Windows и Linux x86_64 запустить на Андроиде который под arm без эмуля?
> 
> я компилировал заранее для arm64 такчто у 60% должно работать... потом я сюда залью исходники и make и сделаю заранее скомпилированые файлы

Посмотрим.

**Comment by modeosr** [comment]
> Посмотрим.
сразу говорю я сюда не повыёбываться пришол ну и ботов начел делать потому что nillerusr ленивая срань.
вот я и вместо него сейчас пилю ботов хотя он и говорил что сделает но не сделал..... если что я ему исходники ищё в начале разработки кидал но ему вижу сейчас похуй. а вот мне не похуй хоть я не играю его порты.....
